--- Makefile	2014-08-12 22:27:22.262848802 +0200
+++ Makefile	2014-08-12 22:27:46.697848621 +0200
@@ -17,7 +17,7 @@
 
 HOSTCC ?= cc
 override CPPFLAGS += -D_GNU_SOURCE
-override CPPFLAGS += -I./libau
+override CPPFLAGS += -I./libau -I./include
 override CPPFLAGS += -DAUFHSM_CMD=\"/usr/bin/aufhsm\"
 override CFLAGS += -O -Wall
 INSTALL ?= install
--- libau/Makefile	2014-08-12 22:39:04.920843618 +0200
+++ libau/Makefile	2014-08-12 22:39:34.378843401 +0200
@@ -30,7 +30,7 @@
 rdu64.o: override CPPFLAGS += -DRdu64
 .INTERMEDIATE.: rdu64.c
 
-${LibSoObj}: override CPPFLAGS += -DNDEBUG -D_REENTRANT -I.
+${LibSoObj}: override CPPFLAGS += -DNDEBUG -D_REENTRANT -I. -I../include
 ${LibSoObj}: override CFLAGS += -fPIC
 ${LibSoObj}: %.o: %.c ${LibSoHdr}
 ${LibSo}: ${LibSo}.${LibSoMajor}
--- fhsm/Makefile	2014-08-12 22:57:32.429835447 +0200
+++ fhsm/Makefile	2014-08-12 22:56:34.028835878 +0200
@@ -35,7 +35,7 @@
 
 ########################################
 
-override CPPFLAGS += -DAUFHSM_LIST_CMD=\"/usr/lib/aufhsm-list\"
+override CPPFLAGS += -DAUFHSM_LIST_CMD=\"/usr/lib/aufhsm-list\" -I../include
 override CPPFLAGS += -DAUFHSMD_CMD=\"/usr/lib/aufhsmd\"
 ${LibFhsmObj}: %.o: %.c ${LibFhsmHdr} $(addprefix ../, ${LibUtilHdr})
 ${LibFhsm}: $(foreach o, ${LibFhsmObj}, ${LibFhsm}(${o}))
