--- Makefile	2015-01-26 10:25:57.484000895 +0100
+++ Makefile	2015-01-26 10:28:17.892002817 +0100
@@ -17,7 +17,7 @@
 
 HOSTCC ?= cc
 override CPPFLAGS += -D_GNU_SOURCE
-override CPPFLAGS += -I./libau
+override CPPFLAGS += -I./libau -I./include
 override CPPFLAGS += -DAUFHSM_CMD=\"/usr/bin/aufhsm\"
 override CFLAGS += -O -Wall
 INSTALL ?= install
--- fhsm/Makefile	2015-01-26 10:27:11.164001904 +0100
+++ fhsm/Makefile	2015-01-26 10:31:03.264005079 +0100
@@ -35,7 +35,7 @@
 
 ########################################
 
-override CPPFLAGS += -DAUFHSM_LIST_CMD=\"/usr/lib/aufhsm-list\"
+override CPPFLAGS += -DAUFHSM_LIST_CMD=\"/usr/lib/aufhsm-list\" -I../include
 override CPPFLAGS += -DAUFHSMD_CMD=\"/usr/lib/aufhsmd\"
 ${LibFhsmObj}: %.o: %.c ${LibFhsmHdr} $(addprefix ../, ${LibUtilHdr})
 ${LibFhsm}: $(foreach o, ${LibFhsmObj}, ${LibFhsm}(${o}))
--- libau/Makefile	2015-01-26 10:27:21.432002044 +0100
+++ libau/Makefile	2015-01-26 10:29:11.096003545 +0100
@@ -30,7 +30,7 @@
 rdu64.o: override CPPFLAGS += -DRdu64
 .INTERMEDIATE.: rdu64.c
 
-${LibSoObj}: override CPPFLAGS += -DNDEBUG -D_REENTRANT -I.
+${LibSoObj}: override CPPFLAGS += -DNDEBUG -D_REENTRANT -I. -I../include
 ${LibSoObj}: override CFLAGS += -fPIC
 ${LibSoObj}: %.o: %.c ${LibSoHdr}
 ${LibSo}: ${LibSo}.${LibSoMajor}
