--- /var/tmp/portage/media-libs/lv2-dyn-manifest-1.0/work/dyn-manifest.lv2/Makefile	2010-10-04 18:09:46.000000000 +0000
+++ /root/Makefile	2011-06-23 16:53:07.985053985 +0000
@@ -1,4 +1,4 @@
-PREFIX = /usr/local
+PREFIX = /usr
 LV2_DIR = $(PREFIX)/lib/lv2
 INCLUDE_DIR = $(PREFIX)/include
 
@@ -9,12 +9,13 @@
 	@echo "make PREFIX=/usr LV2_DIR=/usr/lib/lv2 INCLUDE_DIR=/usr/include"
 	@echo
 	@echo "Defaults:"
-	@echo "    PREFIX      = /usr/local"
+	@echo "    PREFIX      = /usr"
 	@echo "    LV2_DIR     = PREFIX/lib/lv2"
 	@echo "    INCLUDE_DIR = PREFIX/include"
 
 install:
-	install -d $(LV2_DIR)/lv2_dyn_manifest.lv2
-	install -m 0644 lv2_dyn_manifest.ttl $(LV2_DIR)/lv2_dyn_manifest.lv2/
-	install -d $(INCLUDE_DIR)/
-	install -m 0644 lv2_dyn_manifest.h $(INCLUDE_DIR)/
+	install -d $(LV2_DIR)/dyn-manifest
+	install -m 0644 manifest.ttl $(LV2_DIR)/dyn-manifest/
+	install -m 0644 dyn-manifest.ttl $(LV2_DIR)/dyn-manifest/
+	install -d $(INCLUDE_DIR)/lv2plug.in/ns/ext/dyn-manifest/
+	install -m 0644 lv2_dyn_manifest.h $(INCLUDE_DIR)/lv2plug.in/ns/ext/dyn-manifest/
