--- a/Makefile	2012-11-10 16:36:54.621466312 +0100
+++ b/Makefile	2012-11-10 16:39:32.205496239 +0100
@@ -1,2 +1,20 @@
+version        = 0.2.0
+prefix         = /usr
+libdir         = $(get_libdir)
+
+OUT            = bs2b.so
+OBJ            = $(OUT).$(version)
+SRC            = bs2b.c
+
+LIBBS2B_CFLAGS = $(shell pkg-config --cflags libbs2b)
+LIBBS2B_LIBS   = $(shell pkg-config --libs libbs2b)
+CC             = gcc
+CFLAGS         += -Wall -fPIC -std=c99 -shared
+
+define compile
+	$(CC) $(CFLAGS) $(LDFLAGS) -I$(prefix)/include $1 $2 $3 -o $4
+endef
+
 all:
-	gcc -I/usr/local/include  -std=c99 -shared -O2 -o bs2b.so -lbs2b bs2b.c -fPIC -Wall -march=native
+	$(call compile, $(LIBBS2B_CFLAGS), $(LIBBS2B_LIBS), $(SRC), $(OUT))
+
